Regolith 1.0.4
Bedrock-OSS/regolith pull request #252
Opened 2023-02-16 08:54 UTC by stirante

- Implement resolving environment variables for `exact` and `world` export types
 - Added `--update` alias flag to `--force` flag
 - Added `--timings` flag
 - Added filter settings to `when` condition data
 - Added checks for suspicious project location (blocks when in Minecraft data folders and warns when in OneDrive folders)
 - Improve downloading filters
 - Moved info about disabled subfilters to debug
 - Hidden info about nonexistent filter cache, when running from install subcommand
 - Updated go-simple-eval library to fix various bugs when evaluating `when` condition

2023-02-16 20:54 UTC, Nusiq commented
Perhaps we should update the documentation:
- Mentioning new flags - `--update` and `--timings` is not necessary because it's in `--help` and we currently don't have a page in documentation that describes every flag.
- The env variable resolving from 6bb52d88da73e5b7d6bf1b419acd94350bd471e0 could be mentioned in the docs

2023-02-16 20:55 UTC, stirante commented
Ahh right, I completely forgot about the docs

2023-02-16 21:02 UTC, Nusiq requested changes
Don't mark MojangDir as "suspicious path".

2023-02-16 21:04 UTC, Nusiq commented
`go test ./...` fails on my computer on multiple tests. I'm currently checking if it's not something related to my setup.

2023-02-16 21:28 UTC, stirante commented on regolith/compatibility_windows.go
> +	}
How about I limit the check to `development_X_packs` folders? When I was converting a friend to regolith, previously they had a repo just for RP and so the repo was in `development_resource_packs`. Once I converted it to regolith and they pulled the changes, it started breaking.

2023-02-17 17:47 UTC, Nusiq approved these changes

2023-02-17 18:32 UTC, merged